### ISSUE TITLE
If the URL contains Chinese content, the regular expression for extracting links is not reliable.

### ISSUE THREAD

**Issue by cary-rowen** [ibrahim-s/openLinkWith#4]
The following example:

```nvda中文站https://www.nvdacn.com/```

The add-on displays Chinese content in the links list.

**Comment by cary-rowen** [comment]
Hi @ibrahim-s 
We might be able to limit the protocol types that are opened with a regular expression.

What do you think, are you going to fix it?

Best

cary

**Comment by ibrahim-s** [comment]
Hi Cary
Really now I do not have an idea how to fix it
after that I may search and inspect that, after releasing the 
development version of the addon with the added features
I really did not encounter this issue before
but no problem, we will see.
best regards
ibrahim

**Comment by cary-rowen** [comment]
Hi @ibrahim-s 

Don't worry, I'll open a PR to fix this.

Best
